# Generated by Django 3.2.4 on 2021-06-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=30)),
                ('task_desc', models.TextField()),
                ('timme', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
